#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/gulimall_pms?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#    hikari:
#      maximum-pool-size: 3
#      minimumIdle: 1
#
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1
#  application:
#    name: gulimall-product
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#  thymeleaf:
#    cache: false
#
#  redis:
#    host:
#    password:
#  cache:
#    type: redis
#    redis:
#      time-to-live: 3600000 # 毫秒


#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-value: 1 # 逻辑已删除值 默认1
#      logic-not-delete-value: 0 # 逻辑未删除值 默认0

#server:
#  port: 10000

#logging:
#  level:
#    com.wxx.gulimall: debug
