#server:
#  port: 20000
#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  thymeleaf:
#    cache: false
#  redis:
#    host:
#    password:
#    port:
#  session:
#    store-type: redis
#    timeout: 30m
#oAuth2:
#  weibo:
#    clientId:
#    clientSecret: