#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#    alicloud:
#      access-key: LTAI4GKa8FtVxdSp2Kqk4gZt
#      secret-key: po1HBZqtcb1j5KxE7dCsUDztdIBvPZ
#      bucket: wangxin3-gulimall
#      oss:
#        endpoint: oss-cn-beijing.aliyuncs.com
#  application:
#    name: gulimall-third-party

#server:
#  port: 30000